const PUBLIC_SUPABASE_URL = "https://dyrbrnonmwxvggleqdva.supabase.co";
const PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5cmJybm9ubXd4dmdnbGVxZHZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzA1ODM4MzIsImV4cCI6MTk4NjE1OTgzMn0.-gB8ioY2IJdrpW367eqQ9GUWzP7Q50Okgs0tCKWYwwY";
const PUBLIC_STRIPE_SPACE_PRICE = "19";
const PUBLIC_SERVER_URL = "https://new-banks-push-85-7-15-5.loca.lt";
const PUBLIC_SHOT_AMOUNT = "100";
export {
  PUBLIC_STRIPE_SPACE_PRICE as P,
  PUBLIC_SERVER_URL as a,
  PUBLIC_SUPABASE_URL as b,
  PUBLIC_SHOT_AMOUNT as c,
  PUBLIC_SUPABASE_ANON_KEY as d
};
